export const ErrorCode = {
    SOURCE_NOT_FOUND: 'SOURCE_NOT_FOUND',
    INVALID_QR: 'INVALID_QR',
    FEE_EXCEEDED: 'FEE_EXCEEDED',
    UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',
    FILE_WRITE_ERROR: 'FILE_WRITE_ERROR',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    QRIS_TO_SHORT: 'QRIS_TO_SHORT',
    FORMAT_TO_LONG: 'FORMAT_TO_LONG',
    SOURCE_EMPTY: 'SOURCE_EMPTY',
    VALIDATION_FAILED: 'VALIDATION_FAILED'
};